services:
  - type: web
    name: smartbudget-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://swastikkulkarni737:FNhtqkYXsaYUcDT0@cluster0.4uof0n6.mongodb.net/smartbudget?retryWrites=true&w=majority&appName=Cluster0
      - key: SECRET_KEY
        generateValue: true
